services:

    file.storage:
        class:  SAS\IRAD\FileStorageBundle\Service\FileStorageService
        
    file.encrypted_storage:
        class:  SAS\IRAD\FileStorageBundle\Service\EncryptedFileStorageService