parameters:
    file_storage:
        keys:
            public:   "%kernel.root_dir%/config/keys/public.pem"
            private:  "%kernel.root_dir%/config/keys/private.pem"

services:

    storage.file:
        class:  SAS\IRAD\FileStorageBundle\Service\FileStorageService
        
    storage.encrypted:
        class:  SAS\IRAD\FileStorageBundle\Service\EncryptedFileStorageService
        arguments:  [ "%file_storage%" ]